
import type { Patient, Professional, Shift, ShiftHistoryEvent, Transaction, Task, Notification, ShiftReport, InventoryItem, Supply, SupplyRequest } from './types';
import { PlaceHolderImages } from './placeholder-images';
import { format, addDays, startOfWeek, subMonths, subDays } from 'date-fns';
import { ptBR } from 'date-fns/locale';
import { Pill, CircleCheck, CircleX, Stethoscope, TestTube, UserCheck, Heart, CalendarCheck, MapPin, AlertTriangle, Clock } from 'lucide-react';

const patientAvatars = {
  'patient-123': PlaceHolderImages.find(img => img.id === 'patient-avatar-1'),
  'patient-456': PlaceHolderImages.find(img => img.id === 'patient-avatar-2'),
  'patient-789': PlaceHolderImages.find(img => img.id === 'patient-avatar-3'),
};

export const supplies: Supply[] = [
  { id: 'supply-001', name: 'Gaze Estéril', description: 'Pacote com 10 unidades 10x10cm', unit: 'pacote' },
  { id: 'supply-002', name: 'Pomada Antibiótica', description: 'Tubo de 30g', unit: 'tubo' },
  { id: 'supply-003', name: 'Fita Micropore', description: 'Rolo de 2.5cm x 10m', unit: 'rolo' },
  { id: 'supply-004', name: 'Luvas Descartáveis', description: 'Caixa com 100 unidades, tamanho M', unit: 'caixa' },
  { id: 'supply-005', name: 'Soro Fisiológico', description: 'Frasco de 500ml', unit: 'frasco' },
  { id: 'supply-006', name: 'Seringas', description: 'Seringas 10ml, bico Luer Lock', unit: 'caixa' },
  { id: 'supply-007', name: 'Curativos Adesivos', description: 'Curativos tamanho variado', unit: 'caixa' },
  { id: 'supply-008', name: 'Álcool 70%', description: 'Frasco de 1L', unit: 'frasco' },
];

export const patients: Patient[] = [
  {
    id: 'patient-123',
    salutation: 'Sr.',
    firstName: 'João',
    lastName: 'da Silva',
    name: 'João da Silva',
    displayName: 'João',
    initials: 'JS',
    pronouns: 'Ele/Dele',
    avatarUrl: patientAvatars['patient-123']?.imageUrl ?? 'https://picsum.photos/seed/1/100/100',
    avatarHint: patientAvatars['patient-123']?.imageHint ?? 'homem idoso sorrindo',
    photoConsent: { granted: true, grantedBy: 'Maria da Silva (Filha)', date: '2023-01-10T10:00:00Z' },
    identityVerification: {
      status: 'verified',
      method: 'ocr_manual',
      verifiedBy: 'admin',
      verifiedAt: '2024-07-20T12:00:00Z',
    },
    externalIds: {
      crmId: 'crm-0001',
      contractId: 'contrato-2025-00089',
      susId: 'sus-123456',
    },
    
    cpf: '123.456.789-00',
    cpfStatus: 'valid',
    rg: '12.345.678-9',
    rgIssuer: 'SSP/SP',
    rgDigitalUrl: '#',
    cns: '898 0010 8888 1234',
    nationalId: undefined,
    documentValidation: { status: 'validated', validatedBy: 'Admin', validatedAt: '2023-01-11T14:00:00Z', method: 'manual' },

    dateOfBirth: '1945-05-20',
    sexo: 'Masculino',
    sexAtBirth: 'Masculino',
    genderIdentity: 'Masculino',
    estadoCivil: 'Viúvo',
    nacionalidade: 'Brasileiro',
    naturalidade: 'São Paulo/SP',
    placeOfBirth: 'São Paulo/SP',
    preferredLanguage: 'Português',
    riskFlags: ['high-risk', 'do-not-visit-alone'],
    recordStatus: 'active',
    sensitiveDataConsent: {
      granted: true,
      types: ['medical', 'photo'],
      date: '2023-01-10T10:00:00Z',
      grantedBy: 'Maria da Silva',
    },
    duplicateCandidates: [],

    phones: [
      { type: 'mobile', number: '+55 (11) 98888-1111', verified: true, preferred: true },
      { type: 'home', number: '+55 (11) 2222-3333', verified: true, preferred: false },
    ],
    emails: [
        { email: 'joao.silva@example.com', verified: true, preferred: true },
    ],
    preferredContactMethod: 'WhatsApp',
    communicationOptOut: [],

    emergencyContacts: [{
      id: 'ec-1',
      patientId: 'patient-123',
      name: 'Maria da Silva',
      relationship: 'Filha',
      phone: '+55 (11) 98765-4321',
      email: 'maria.filha@example.com',
      isLegalRepresentative: true,
      permissions: { view: true, authorize: true, clinical: true, financial: true },
      notifications: [
        { id: 'ecn-1', contact_id: 'ec-1', channel: 'whatsapp', enabled: true },
        { id: 'ecn-2', contact_id: 'ec-1', channel: 'email', enabled: true },
      ],
      documentUrl: '#'
    }],
    legalGuardian: {
      name: 'Maria da Silva',
      document: 'CPF: 111.222.333-44',
      documentType: 'Procuração',
      powerOfAttorneyUrl: '#',
    },

    address: {
      street: 'Rua das Flores',
      number: '123',
      complement: 'Apto 45',
      neighborhood: 'Centro',
      city: 'São Paulo',
      state: 'SP',
      zipCode: '01001-000',
      pontoReferencia: 'Próximo à padaria Flor do Dia',
      zoneType: 'Urbana',
      gateIdentification: 'Apto 45, Sr. João',
      allowedVisitHours: '08:00 - 20:00',
      localSafetyConditions: 'Bairro tranquilo, bem iluminado.',
      facadeImageUrl: 'https://picsum.photos/seed/fachada1/400/300',
      geolocation: { lat: -23.55052, lng: -46.633308 },
      etaMinutes: 35,
      travelNotes: 'Evitar horários de pico devido ao trânsito.'
    },
     domicile: {
      tipoResidencia: 'Apartamento',
      floor: 4,
      hasElevator: true,
      internalAccess: 'Corredores largos, sem escadas internas.',
      patientRoom: 'Quarto principal',
      hasAdaptedBathroom: true,
      ambulanceAccess: 'Fácil',
      teamParking: 'Restrito',
      entryProcedure: 'Interfonar no 45, portaria 24h.',
      nightAccessRisk: 'Baixo',
      pets: 'Nenhum',
      hygieneConditions: 'Boa',
      hasSmokers: false,
      ventilation: 'Adequada',
      noiseLevel: 'Baixo',
      hasWifi: true,
      backupPowerSource: 'Inexistente',
      waterSource: 'Rede Pública',
      electricalInfrastructure: 'Tomadas 110V e 220V disponíveis no quarto.',
      otherResidents: [{name: 'Maria da Silva', relationship: 'Filha (visitas diárias)'}],
      fixedCaregivers: 'Nenhum',
      environmentalRisks: 'Nenhum identificado',
      generalObservations: 'Apartamento bem organizado e limpo.',
      caregivers: [
        { name: 'Fernanda A.', schedule: 'Diurno 12x36', role: 'Cuidadora' },
        { name: 'Claudio B.', schedule: 'Noturno 12x36', role: 'Cuidador' },
      ],
      careTeamEtaMinutes: 40,
      etaSource: 'Google Maps',
      logisticNotes: 'Portaria exige documento com foto.',
      animalsBehavior: 'Sem animais',
      environmentNotes: 'Ótima iluminação natural.',
    },
    clinicalSummary: {
      diagnosisPrimary: { name: 'DPOC', cid: 'J44.9' },
      allergies: [
        { substance: 'Penicilina', severity: 'grave', reaction: 'Anafilaxia', recordedAt: '2019-03-10' }
      ],
      criticalMedications: [
        { name: 'Losartana', note: 'Monitorar PA' },
        { name: 'Metformina', note: 'Administrar com refeições' }
      ],
      devicesActive: [],
      oxygenTherapy: { active: false },
      riskScores: {
        falls: 45,
        fallsLabel: 'Médio',
        braden: 18,
        bradenLabel: 'Risco Baixo'
      },
      lastReview: { date: '2025-10-15', by: 'Carla Nogueira (enf)' },
      shortNote: 'Paciente com mobilidade reduzida, aguardando avaliação da fisioterapia.',
      alerts: [
        { type: 'ALERGIA', message: 'Penicilina - Risco de Anafilaxia', severity: 'CRITICAL' }
      ]
    },
    clinicalSummaryMeta: {
        lastUpdatedAt: '2025-10-15T09:03:00Z',
        lastUpdatedBy: 'user-234',
        source: 'prontuario'
    },
    clinicalData: {
        medications: [
            { name: 'Losartana', dosage: '50mg', frequency: '2x/dia', notes: 'Monitorar PA' },
            { name: 'Metformina', dosage: '500mg', frequency: '2x/dia', notes: 'Administrar com refeições' },
        ],
    },
    financial: {
        vinculo: 'Plano de Saúde',
        bondType: 'Plano de Saúde',
        operadora: 'Amil 700',
        carteirinha: '987654321-0',
        validadeCarteirinha: '2025-12-31',
        monthlyFee: 1200,
        billingDay: 10,
        formaPagamento: 'Débito automático',
        paymentMethod: 'Débito automático',
        billingStatus: 'Pago',
        lastPaymentDate: '2025-10-10',
        paymentHistory: [
          { month: '2025-10', status: 'Pago', amount: 1200, paidAt: '2025-10-10', method: 'Débito' },
          { month: '2025-09', status: 'Pago', amount: 1200, paidAt: '2025-09-10', method: 'Débito' },
          { month: '2025-08', status: 'Pago', amount: 1200, paidAt: '2025-08-10', method: 'Débito' },
          { month: '2025-07', status: 'Pago', amount: 1200, paidAt: '2025-07-10', method: 'Débito' },
          { month: '2025-06', status: 'Pago', amount: 1200, paidAt: '2025-06-10', method: 'Débito' },
        ],
        observacoesFinanceiras: 'Financeiro em dia. Plano cobre materiais.',
    },
    adminData: { 
        status: 'Ativo', 
        complexity: 'Alta', 
        servicePackage: 'Completo', 
        startDate: '2023-01-10', 
        supervisorId: 'prof-1', 
        escalistaId: 'prof-5', 
        admissionType: 'Home Care',
        frequency: 'Diário (24h)',
        operationArea: 'SP Capital - Zona Sul',
        admissionSource: 'Hospital São Luiz',
        contractId: 'HSJ-2023-001A',
        lastAuditDate: '2024-07-15'
    },
    documents: {},
    documentsCollection: [
      {
        id: 'doc-rg-001',
        type: 'RG',
        category: 'Identificacao',
        title: 'RG Paciente',
        description: 'Documento oficial de identificação',
        fileUrl: '#',
        fileName: 'rg-joao.pdf',
        mimeType: 'application/pdf',
        uploadedBy: 'user-001',
        uploadedAt: '2025-08-01T10:30:00Z',
        expiresAt: '2030-08-01',
        verified: true,
        verifiedBy: 'user-010',
        verifiedAt: '2025-08-02T09:00:00Z',
        source: 'upload',
        tags: ['RG', 'Identificação'],
        hash: 'abc123rg'
      },
      {
        id: 'doc-carteirinha-001',
        type: 'CarteirinhaPlano',
        category: 'Financeiro',
        title: 'Carteirinha Amil',
        description: 'Carteirinha válida para autorizações',
        fileUrl: '#',
        fileName: 'carteirinha-amil.pdf',
        mimeType: 'application/pdf',
        uploadedBy: 'user-002',
        uploadedAt: '2025-08-05T09:00:00Z',
        expiresAt: '2025-12-31',
        verified: false,
        source: 'upload',
        tags: ['Operadora', 'Financeiro'],
        hash: 'hashcarteirinha'
      },
      {
        id: 'doc-contrato-001',
        type: 'ContratoPrestacaoServicos',
        category: 'Juridico',
        title: 'Contrato Home Care 2025',
        description: 'Contrato padrão Conecta Care',
        fileUrl: '#',
        fileName: 'contrato-homecare-2025.pdf',
        mimeType: 'application/pdf',
        uploadedBy: 'user-legal-01',
        uploadedAt: '2025-07-28T14:12:00Z',
        verified: true,
        verifiedBy: 'user-legal-05',
        verifiedAt: '2025-07-29T10:00:00Z',
        source: 'assinaturaDigital',
        tags: ['Contrato', 'Jurídico'],
        hash: 'hashcontrato2025'
      },
      {
        id: 'doc-consent-lgpd-001',
        type: 'TermoConsentimento',
        category: 'Consentimento',
        title: 'Consentimento LGPD Geral',
        description: 'Termo padrão de tratamento de dados',
        fileUrl: '#',
        fileName: 'consentimento-lgpd.pdf',
        mimeType: 'application/pdf',
        uploadedBy: 'user-ops-02',
        uploadedAt: '2025-08-01T11:00:00Z',
        verified: true,
        verifiedBy: 'user-ops-02',
        verifiedAt: '2025-08-01T11:02:00Z',
        source: 'assinaturaDigital',
        tags: ['LGPD'],
        hash: 'hashlgpd'
      }
    ],
    consents: [
      {
        id: 'cons-lgpd-001',
        type: 'TratamentoDadosLGPD',
        scope: ['DadosClinicos', 'DadosFinanceiros', 'EnvioComunicacoes'],
        status: 'Ativo',
        grantedAt: '2025-08-01T11:00:00Z',
        channel: 'AssinaturaDigital',
        documentId: 'doc-consent-lgpd-001',
        grantedBy: 'ResponsavelLegal',
        grantedByName: 'Maria da Silva',
        grantedByDocument: '123.456.789-00',
        relatedLegalResponsibleId: 'ec-1',
        notes: 'Consentimento padrão de entrada no programa.'
      },
      {
        id: 'cons-whatsapp-001',
        type: 'EnvioComunicacoesWhatsApp',
        scope: ['EnvioComunicacoes'],
        status: 'Ativo',
        grantedAt: '2025-08-01T11:05:00Z',
        channel: 'Aplicativo',
        grantedBy: 'Paciente',
        grantedByName: 'João da Silva',
        notes: 'Autorizado durante onboarding digital.'
      },
      {
        id: 'cons-familia-001',
        type: 'CompartilhamentoComFamiliares',
        scope: ['CompartilhamentoComTerceiros', 'DadosClinicos'],
        status: 'Revogado',
        grantedAt: '2024-05-10T08:30:00Z',
        revokedAt: '2025-01-15T09:00:00Z',
        channel: 'Manual',
        grantedBy: 'ResponsavelLegal',
        grantedByName: 'Maria da Silva',
        notes: 'Revogado após atualização de responsáveis.'
      }
    ],
    changeLog: [
      {
        id: 'chg-001',
        patientId: 'patient-123',
        type: 'edit',
        action: 'Atualização de status e complexidade',
        userId: 'user-010',
        userRole: 'Supervisor',
        timestamp: '2025-10-16T11:30:00Z',
        origin: 'web',
        changedFields: ['adminData.status', 'adminData.complexity'],
        meta: {
          old: { status: 'Ativo', complexity: 'Média' },
          new: { status: 'Ativo', complexity: 'Alta' },
          reason: 'Reavaliação clínica',
        },
      },
      {
        id: 'chg-002',
        patientId: 'patient-123',
        type: 'status_change',
        action: 'Atualização de pacote',
        userId: 'user-015',
        userRole: 'Financeiro',
        timestamp: '2025-10-18T09:20:00Z',
        origin: 'web',
        changedFields: ['adminData.servicePackage'],
        meta: {
          old: { servicePackage: 'Intermediário' },
          new: { servicePackage: 'Completo' },
          reason: 'Solicitação familiar',
        },
      },
    ],
    accessLog: [
      {
        id: 'acc-001',
        patientId: 'patient-123',
        type: 'view',
        action: 'Visualização completa da ficha',
        userId: 'user-020',
        userRole: 'Financeiro',
        timestamp: '2025-10-20T09:10:00Z',
        origin: 'web',
        meta: { section: 'financial', reason: 'Análise de cobrança' },
      },
      {
        id: 'acc-002',
        patientId: 'patient-123',
        type: 'export',
        action: 'Exportação PDF Plano de Cuidados',
        userId: 'user-031',
        userRole: 'Compliance',
        timestamp: '2025-10-22T15:45:00Z',
        origin: 'web',
        meta: { format: 'PDF', scope: 'Prontuário completo' },
      },
      {
        id: 'acc-003',
        patientId: 'patient-123',
        type: 'download',
        action: 'Download carteira plano',
        userId: 'user-022',
        userRole: 'Autorização',
        timestamp: '2025-10-23T08:12:00Z',
        origin: 'web',
        meta: { documentId: 'doc-carteirinha-001' },
      },
    ],
    smartFields: {
      readmissionRiskScore: {
        value: 0.78,
        label: 'Alto',
        lastUpdatedAt: '2025-10-20T10:00:00Z',
        source: 'ai-model-v1',
      },
      careAdherenceScore: {
        value: 0.65,
        label: 'Moderada',
        lastUpdatedAt: '2025-10-19T18:00:00Z',
        source: 'rules-engine',
      },
      familySatisfactionScore: {
        value: 9.1,
        label: 'Alta',
        lastSurveyAt: '2025-09-30',
        surveyId: 'survey-2025-09-001',
      },
      incidentsLast30Days: {
        count: 2,
        lastIncidentAt: '2025-10-10',
      },
      environmentAdequacyScore: {
        value: 0.82,
        label: 'Excelente',
        lastUpdatedAt: '2025-10-18T13:00:00Z',
        source: 'environment-iad',
      },
    },
    operationalLinks: {
      contractId: 'contrato-2025-00089',
      rosterId: 'escala-2025-10-001',
      inventoryId: 'estoque-cuid-0005',
      publicProtocolUrl: 'https://protocolo.conectacare.com/p/abc123',
      accessLogRef: 'log-patient-123',
    },
    lastViewedAt: '2025-10-22T15:45:00Z',
    accessLogSummary: {
      totalViews: 32,
      totalExports: 4,
      lastAccessAt: '2025-10-22T15:45:00Z',
      lastAccessBy: 'user-031',
    },
    audit: { createdAt: '2023-01-10T10:00:00Z', createdBy: 'Admin', updatedAt: '2024-07-20T15:00:00Z', updatedBy: 'Carla Nogueira' },
    
    last_visit_date: subDays(new Date(), 1).toISOString(),
    next_visit_date: addDays(new Date(), 1).toISOString(),
    consent_status: 'ok',
    pending_documents: 0,
  },
  {
    id: 'patient-456',
    salutation: 'Sra.',
    firstName: 'Maria',
    lastName: 'Lopes',
    name: 'Maria Lopes',
    initials: 'ML',
    displayName: 'Maria',
    pronouns: 'Ela/Dela',
    avatarUrl: patientAvatars['patient-456']?.imageUrl ?? 'https://picsum.photos/seed/2/100/100',
    avatarHint: patientAvatars['patient-456']?.imageHint ?? 'senhora de oculos',
    nacionalidade: 'Brasileira',
    naturalidade: 'Rio de Janeiro/RJ',
    photoConsent: undefined,
    identityVerification: {
      status: 'pending',
      method: 'ocr',
    },
    externalIds: {
      crmId: 'crm-0002',
      rosterId: 'escala-2025-09-010',
    },
    genderIdentity: 'Feminino',
    preferredLanguage: 'Português',

    cpf: '987.654.321-00',
    cns: '700 5081 1234 5678',
    cpfStatus: 'valid',
    documentValidation: { status: 'pending' },

    dateOfBirth: '1942-11-15',
    sexo: 'Feminino',
    sexAtBirth: 'Feminino',
    estadoCivil: 'Casada',
    
    phones: [
        { type: 'home', number: '+55 (21) 2222-7777', verified: true, preferred: true },
        { type: 'mobile', number: '+55 (21) 97777-2222', verified: true, preferred: false },
    ],
    emails: [{ email: 'maria.lopes@example.com', verified: true, preferred: true }],
    preferredContactMethod: 'Telefone',
    communicationOptOut: [{type: 'sms', optedOut: true, date: '2024-01-01T00:00:00Z'}],

    emergencyContacts: [{
        id: 'ec-2',
        patientId: 'patient-456',
        name: 'Carlos Lopes',
        relationship: 'Filho',
        phone: '+55 (21) 91234-5678',
        email: 'carlos.lopes@example.com',
        isLegalRepresentative: true,
        permissions: { view: true, authorize: true, financial: true },
        notifications: [
          { id: 'ecn-3', contact_id: 'ec-2', channel: 'whatsapp', enabled: true },
          { id: 'ecn-4', contact_id: 'ec-2', channel: 'email', enabled: false },
        ],
    }],
    legalGuardian: undefined,
    
    address: {
      street: 'Avenida Copacabana',
      number: '1000',
      complement: 'Apto 101',
      neighborhood: 'Copacabana',
      city: 'Rio de Janeiro',
      state: 'RJ',
      zipCode: '22020-002',
      pontoReferencia: 'Próximo ao Copacabana Palace',
      geolocation: { lat: -22.971177, lng: -43.182543 },
      etaMinutes: 55,
    },
    domicile: {
      pets: '1 gato persa, tranquilo.',
      caregivers: [{ name: 'Luciana M.', schedule: 'Seg-Sex 8h-18h', role: 'Cuidadora' }],
      careTeamEtaMinutes: 50,
      logisticNotes: 'Portaria exige documento e cadastro prévio.',
      animalsBehavior: 'Gato dócil, fica em quartos.',
    },
    clinicalSummary: {} as any, // Placeholder
    clinicalSummaryMeta: {} as any, // Placeholder
    clinicalData: { medications: [] },
    financial: {
        vinculo: 'Particular',
        bondType: 'Particular',
        monthlyFee: 8500,
        billingDay: 5,
        formaPagamento: 'Boleto',
        paymentMethod: 'Transferência',
        billingStatus: 'Pendente',
        lastPaymentDate: '2025-09-05',
        paymentHistory: [
          { month: '2025-10', status: 'Pendente', amount: 8500 },
          { month: '2025-09', status: 'Pago', amount: 8500, paidAt: '2025-09-05', method: 'Pix' },
          { month: '2025-08', status: 'Pago', amount: 8500, paidAt: '2025-08-05', method: 'Pix' },
          { month: '2025-07', status: 'Pago', amount: 8500, paidAt: '2025-07-05', method: 'Pix' },
        ],
        observacoesFinanceiras: 'Cliente particular – enviar nota fiscal mensal.',
    },
    adminData: { status: 'Ativo', complexity: 'Média', servicePackage: 'Intermediário', startDate: '2023-05-20', supervisorId: 'prof-3', admissionType: 'Acompanhamento Ambulatorial', frequency: '3x por semana'},
    documents: {
        termoLgpdUrl: '#'
    },
    documentsCollection: [],
    consents: [],
    changeLog: [
      {
        id: 'chg-101',
        patientId: 'patient-456',
        type: 'edit',
        action: 'Atualização de endereço',
        userId: 'user-040',
        userRole: 'Operacional',
        timestamp: '2025-01-05T10:15:00Z',
        origin: 'web',
        changedFields: ['address.street', 'address.number'],
      },
    ],
    accessLog: [
      {
        id: 'acc-101',
        patientId: 'patient-456',
        type: 'view',
        action: 'Consulta de prontuário',
        userId: 'user-050',
        userRole: 'Equipe Clínica',
        timestamp: '2025-01-06T08:00:00Z',
        origin: 'mobile',
        meta: { section: 'clinical' },
      },
    ],
    smartFields: {
      readmissionRiskScore: {
        value: 0.42,
        label: 'Moderado',
        lastUpdatedAt: '2025-09-15T08:00:00Z',
        source: 'ai-model-v1',
      },
      careAdherenceScore: {
        value: 0.72,
        label: 'Alta',
        lastUpdatedAt: '2025-09-18T18:30:00Z',
        source: 'rules-engine',
      },
      incidentsLast30Days: {
        count: 0,
      },
      environmentAdequacyScore: {
        value: 0.6,
        label: 'Moderada',
        lastUpdatedAt: '2025-09-18T18:30:00Z',
        source: 'environment-iad',
      },
    },
    operationalLinks: {
      contractId: 'contrato-2024-00012',
      rosterId: 'escala-2025-09-010',
      inventoryId: 'estoque-cuid-0010',
      accessLogRef: 'log-patient-456',
    },
    recordStatus: 'active',
    riskFlags: ['oxygen-therapy'],
    sensitiveDataConsent: {
      granted: true,
      types: ['medical'],
      date: '2024-03-02T12:30:00Z',
      grantedBy: 'Carlos Lopes',
    },
    duplicateCandidates: [],
    lastViewedAt: '2025-01-06T08:00:00Z',
    accessLogSummary: {
      totalViews: 8,
      totalExports: 1,
      lastAccessAt: '2025-01-06T08:00:00Z',
      lastAccessBy: 'user-050',
    },
    audit: { createdAt: '2023-05-20T11:00:00Z', createdBy: 'Admin', updatedAt: '2024-07-19T10:00:00Z', updatedBy: 'Admin' },

    last_visit_date: subDays(new Date(), 5).toISOString(),
    next_visit_date: addDays(new Date(), 3).toISOString(),
    consent_status: 'pending',
    pending_documents: 1,
  },
  {
    id: 'patient-789',
    salutation: 'Sr.',
    firstName: 'Jorge',
    lastName: 'Mendes',
    name: 'Jorge Mendes',
    initials: 'JM',
    displayName: 'Jorge',
    pronouns: 'Ele/Dele',
    cpf: '111.222.333-44',
    cpfStatus: 'unknown',
    dateOfBirth: '1959-03-01',
    avatarUrl: patientAvatars['patient-789']?.imageUrl ?? 'https://picsum.photos/seed/3/100/100',
    avatarHint: patientAvatars['patient-789']?.imageHint ?? 'homem de meia idade',
    documentValidation: { status: 'none' },
    identityVerification: { status: 'none' },
    externalIds: {
      inventoryId: 'estoque-cuid-0002',
    },

    sexAtBirth: 'Masculino',
    naturalidade: 'Belo Horizonte/MG',
    placeOfBirth: 'Belo Horizonte/MG',
    phones: [{ type: 'mobile', number: '+55 (31) 96666-3333', verified: false, preferred: true }],
    emails: [{ email: 'jorge.mendes@example.com', verified: false, preferred: true }],
    
    emergencyContacts: [{
        id: 'ec-3',
        patientId: 'patient-789',
        name: 'Ana Mendes',
        relationship: 'Esposa',
        phone: '+55 (31) 95555-8888',
        email: 'ana.mendes@example.com',
        isLegalRepresentative: true,
        permissions: { view: true, authorize: true, clinical: true },
        notifications: [
          { id: 'ecn-5', contact_id: 'ec-3', channel: 'sms', enabled: true },
          { id: 'ecn-6', contact_id: 'ec-3', channel: 'whatsapp', enabled: false },
        ],
    }],
    legalGuardian: undefined,
    
    address: {
      street: 'Rua da Bahia',
      number: '500',
      neighborhood: 'Savassi',
      city: 'Belo Horizonte',
      state: 'MG',
      zipCode: '30130-001',
      pontoReferencia: '',
      geolocation: { lat: -19.933, lng: -43.9309 },
      etaMinutes: 25,
    },
    domicile: {
      tipoResidencia: 'Casa',
      hasElevator: false,
      ambulanceAccess: 'Médio',
      teamParking: 'Disponível',
      entryProcedure: 'Chamar pelo interfone e aguardar acompanhante.',
      nightAccessRisk: 'Médio',
      pets: 'Dois cachorros de médio porte',
      caregivers: [{ name: 'Agência Alfa', schedule: 'Plantão eventual', role: 'Suporte' }],
      careTeamEtaMinutes: 30,
      animalsBehavior: 'Cães agitados, precisam ser presos durante a visita',
      environmentNotes: 'Casa térrea em reforma parcial.',
    },
    clinicalSummary: {} as any, // Placeholder
    clinicalSummaryMeta: {} as any, // Placeholder
    clinicalData: { medications: [] },
    financial: {
        vinculo: 'Plano de Saúde',
        operadora: 'Unimed Flex',
        carteirinha: '11223344-5',
        monthlyFee: 950,
        billingDay: 15,
    },
    adminData: { 
        status: 'Inativo', 
        complexity: 'Baixa', 
        servicePackage: 'Básico', 
        startDate: '2024-01-15', 
        endDate: '2024-06-30', 
        supervisorId: 'prof-1', 
        escalistaId: 'prof-5', 
        admissionType: 'Acompanhamento Ambulatorial',
        frequency: '2x por mês'
    },
    documents: {},
    documentsCollection: [
      {
        id: 'doc-rg-003',
        type: 'RG',
        category: 'Identificacao',
        title: 'RG paciente Jorge',
        fileUrl: '#',
        fileName: 'rg-jorge.pdf',
        mimeType: 'application/pdf',
        uploadedBy: 'user-ops-06',
        uploadedAt: '2024-02-10T09:20:00Z',
        verified: false,
        source: 'upload',
        tags: ['Identificação'],
      },
      {
        id: 'doc-alta-001',
        type: 'RelatorioTecnico',
        category: 'Clinico',
        title: 'Relatório de alta',
        fileUrl: '#',
        fileName: 'relatorio-alta-jorge.pdf',
        mimeType: 'application/pdf',
        uploadedBy: 'user-030',
        uploadedAt: '2024-06-28T14:45:00Z',
        verified: true,
        verifiedBy: 'user-030',
        verifiedAt: '2024-06-28T14:50:00Z',
        source: 'upload',
      },
    ],
    consents: [
      {
        id: 'cons-lgpd-003',
        type: 'TratamentoDadosLGPD',
        scope: ['DadosClinicos'],
        status: 'Expirado',
        grantedAt: '2024-01-15T12:00:00Z',
        revokedAt: '2024-07-01T09:00:00Z',
        channel: 'Manual',
        grantedBy: 'ResponsavelLegal',
        grantedByName: 'Ana Mendes',
      },
    ],
    changeLog: [
      {
        id: 'chg-201',
        patientId: 'patient-789',
        type: 'status_change',
        action: 'Encerramento do cuidado',
        userId: 'user-015',
        userRole: 'Supervisor',
        timestamp: '2024-06-30T18:00:00Z',
        origin: 'web',
        changedFields: ['adminData.status', 'adminData.endDate'],
        meta: { new: { status: 'Inativo' } },
      },
    ],
    accessLog: [],
    smartFields: {
      readmissionRiskScore: {
        value: 0.15,
        label: 'Baixo',
        lastUpdatedAt: '2024-06-30T18:00:00Z',
        source: 'ai-model-v1',
      },
      familySatisfactionScore: {
        value: 8.4,
        label: 'Alta',
        lastSurveyAt: '2024-05-01',
        surveyId: 'survey-2024-05-010',
      },
      incidentsLast30Days: {
        count: 0,
      },
      environmentAdequacyScore: {
        value: 0.45,
        label: 'Baixa',
        lastUpdatedAt: '2024-06-25T09:00:00Z',
        source: 'environment-iad',
      },
    },
    operationalLinks: {
      contractId: 'contrato-2024-00444',
      inventoryId: 'estoque-cuid-0002',
      publicProtocolUrl: 'https://protocolo.conectacare.com/p/xyz999',
      accessLogRef: 'log-patient-789',
    },
    audit: { createdAt: '2024-01-15T09:00:00Z', createdBy: 'Admin', updatedAt: '2024-06-30T18:00:00Z', updatedBy: 'Admin' },
    recordStatus: 'inactive',
    riskFlags: ['recent-discharge'],
    sensitiveDataConsent: {
      granted: false,
      types: [],
      date: '2024-01-15T12:00:00Z',
      grantedBy: 'Ana Mendes',
    },
    duplicateCandidates: ['patient-123'],
    lastViewedAt: '2024-06-30T18:00:00Z',
    accessLogSummary: {
      totalViews: 4,
      totalExports: 1,
      lastAccessAt: '2024-06-30T18:00:00Z',
      lastAccessBy: 'user-015',
    },
    
    last_visit_date: subDays(new Date(), 30).toISOString(),
    consent_status: 'ok',
    pending_documents: 3,
  },
];

export const professionals: Professional[] = [
  {
    id: 'prof-1',
    name: 'Carla Nogueira',
    initials: 'CN',
    email: 'carla.n@conectacare.com',
    phone: '+55 11 91234-5678',
    cpf: '222.333.444-55',
    dateOfBirth: '1985-10-25',
    address: { street: 'Rua das Enfermeiras', number: '10', neighborhood: 'Centro', city: 'São Paulo', state: 'SP', zipCode: '04300-000' },
    avatarUrl: 'https://picsum.photos/seed/prof1/100/100',
    avatarHint: 'woman nurse smiling',
    rating: 4.8,
    bio: 'Enfermeira com mais de 10 anos de experiência em home care, especializada no cuidado de pacientes idosos e com doenças crônicas. Focada em um atendimento humanizado e de alta qualidade.',
    coren: 'SP-123456-ENF',
    corenStatus: 'active',
    role: 'Supervisor(a)',
    employmentType: 'externo',
    specialties: ['Home Care', 'Geriatria', 'Administração de Medicamentos IV', 'Curativos'],
    reviews: [
      { from: 'Família Silva', quote: 'Profissional exemplar, sempre pontual e muito carinhosa com nosso pai.' },
      { from: 'Home Care ABC', quote: 'Uma das melhores enfermeiras da nossa equipe. Proativa e muito competente.' }
    ],
    compatibilityTags: [
        { text: 'Já atendeu este paciente', icon: UserCheck, variant: 'positive' },
        { text: 'Atende no mesmo bairro', icon: MapPin, variant: 'positive' }
    ],
    lastActivity: 'Ativo(a) há 15 minutos',
    recentAttendances: [
        { patientName: 'João da Silva', date: '2d atrás', note: '⭐️ 5.0 | Plantão tranquilo.' },
        { patientName: 'Sônia Braga', date: '5d atrás', note: '⭐️ 4.8 | Sem intercorrências.' },
    ]
  },
  {
    id: 'prof-2',
    name: 'Fábio Bastos',
    initials: 'FB',
    email: 'fabio.b@conectacare.com',
    phone: '+55 21 92345-6789',
    cpf: '333.444.555-66',
    dateOfBirth: '1992-02-18',
    address: { street: 'Av. das Américas', number: '2000', neighborhood: 'Barra da Tijuca', city: 'Rio de Janeiro', state: 'RJ', zipCode: '22640-100' },
    avatarUrl: 'https://picsum.photos/seed/prof2/100/100',
    avatarHint: 'male nurse smiling',
    rating: 4.5,
    bio: 'Técnico de enfermagem com 5 anos de experiência em ambiente hospitalar e home care. Habilidade em curativos complexos e monitoramento de pacientes.',
    coren: 'RJ-654321-TEC',
    corenStatus: 'active',
    role: 'Cuidador(a)',
    employmentType: 'fixo',
    specialties: ['Curativos Complexos', 'Monitoramento de Sinais Vitais'],
    reviews: [
        { from: 'Hospital Central', quote: 'Muito atencioso e técnico. Um ótimo profissional para se ter na equipe.' },
    ],
    compatibilityTags: [],
  },
  {
    id: 'prof-3',
    name: 'Diogo Lima',
    initials: 'DL',
    email: 'diogo.l@conectacare.com',
    phone: '+55 31 93456-7890',
    cpf: '444.555.666-77',
    dateOfBirth: '1988-07-30',
    address: { street: 'Rua dos Inconfidentes', number: '50', neighborhood: 'Funcionários', city: 'Belo Horizonte', state: 'MG', zipCode: '30140-120' },
    avatarUrl: 'https://picsum.photos/seed/prof3/100/100',
    avatarHint: 'male nurse glasses',
    rating: 4.9,
    bio: 'Enfermeiro com vasta experiência em UTI e cuidados intensivos. Especialista em ventilação mecânica e pacientes de alta complexidade.',
    coren: 'MG-112233-ENF',
    corenStatus: 'active',
    role: 'Supervisor(a)',
    employmentType: 'interno',
    specialties: ['UTI', 'Ventilação Mecânica', 'Cuidados Paliativos'],
    reviews: [],
    compatibilityTags: [],
  },
    {
    id: 'prof-4',
    name: 'Diana Magalhães',
    initials: 'DM',
    email: 'diana.m@conectacare.com',
    phone: '+55 11 94567-8901',
    cpf: '555.666.777-88',
    dateOfBirth: '1998-12-05',
    address: { street: 'Rua Augusta', number: '900', neighborhood: 'Consolação', city: 'São Paulo', state: 'SP', zipCode: '01304-001' },
    avatarUrl: 'https://picsum.photos/seed/prof4/100/100',
    avatarHint: 'young woman nurse',
    rating: 3.2,
    bio: 'Recém-formada em enfermagem, com foco em pediatria. Buscando ganhar experiência em home care.',
    coren: 'SP-998877-ENF',
    corenStatus: 'inactive',
    role: 'Cuidador(a)',
    employmentType: 'externo',
    specialties: ['Pediatria'],
    reviews: [
         { from: 'Hospital Infantil', quote: 'Atrasou em 2 dos 3 plantões alocados.' },
    ],
    compatibilityTags: [
        { text: 'Disponível apenas noturno', icon: AlertTriangle, variant: 'warning' },
    ],
    lastActivity: 'Offline',
  },
  {
    id: 'prof-5',
    name: 'Bruno Alves',
    initials: 'BA',
    email: 'bruno.a@conectacare.com',
    phone: '+55 41 95678-9012',
    cpf: '666.777.888-99',
    dateOfBirth: '1980-04-12',
    address: { street: 'Rua das Araucárias', number: '150', neighborhood: 'Batel', city: 'Curitiba', state: 'PR', zipCode: '80420-190' },
    avatarUrl: 'https://picsum.photos/seed/prof5/100/100',
    avatarHint: 'male nurse serious',
    rating: 4.7,
    bio: 'Enfermeiro experiente na área de cardiologia, com passagens por grandes hospitais. Agora focado em home care para reabilitação cardíaca.',
    coren: 'PR-445566-ENF',
    corenStatus: 'active',
    role: 'Escalista',
    employmentType: 'interno',
    specialties: ['Cardiologia', 'Home Care', 'Reabilitação'],
    reviews: [
      { from: 'Clínica do Coração', quote: 'Excelente profissional, muito conhecimento técnico e ótimo com os pacientes.' },
    ],
    compatibilityTags: [{ text: 'Disponível no período', icon: CalendarCheck, variant: 'positive' }],
    lastActivity: 'Ativo(a) há 2 horas',
  },
  {
    id: 'prof-6',
    name: 'Juliana Paes',
    initials: 'JP',
    email: 'juliana.p@conectacare.com',
    phone: '+55 51 96789-0123',
    cpf: '777.888.999-00',
    dateOfBirth: '1995-09-01',
    address: { street: 'Av. Ipiranga', number: '3000', neighborhood: 'Partenon', city: 'Porto Alegre', state: 'RS', zipCode: '90610-000' },
    avatarUrl: 'https://picsum.photos/seed/prof6/100/100',
    avatarHint: 'woman nurse glasses',
    rating: 4.9,
    bio: 'Especialista em dermatologia e tratamento de lesões de pele. Muito cuidadosa e atenta aos detalhes, ideal para pacientes com necessidade de curativos especiais.',
    coren: 'RS-778899-ENF',
    corenStatus: 'active',
    role: 'Cuidador(a)',
    employmentType: 'externo',
    specialties: ['Dermatologia', 'Curativos Especiais', 'Lesões por Pressão'],
    reviews: [
      { from: 'DermaClin', quote: 'Extremamente cuidadosa e atenta aos detalhes.' },
      { from: 'Home Care Senior', quote: 'Paciente adorou a atenção e o cuidado.' }
    ],
    compatibilityTags: [
        { text: 'Especialista em Curativos', icon: Heart, variant: 'positive' }
    ],
    lastActivity: 'Online',
  },
  {
    id: 'prof-7',
    name: 'Ricardo Gomes',
    initials: 'RG',
    email: 'ricardo.g@conectacare.com',
    phone: '+55 71 97890-1234',
    cpf: '888.999.000-11',
    dateOfBirth: '1990-06-20',
    address: { street: 'Av. Oceânica', number: '400', neighborhood: 'Barra', city: 'Salvador', state: 'BA', zipCode: '40140-130' },
    avatarUrl: 'https://picsum.photos/seed/prof7/100/100',
    avatarHint: 'male physiotherapist',
    rating: 4.3,
    bio: 'Fisioterapeuta com foco em reabilitação respiratória e motora. Experiência com pacientes pós-AVC e com doenças neuromusculares.',
    coren: 'BA-223344-FST',
    corenStatus: 'active',
    role: 'Fisioterapeuta',
    employmentType: 'fixo',
    specialties: ['Fisioterapia Respiratória', 'Fisioterapia Motora'],
    reviews: [],
    compatibilityTags: [],
  }
];

const today = new Date();
const startOfCurrentWeek = startOfWeek(today, { weekStartsOn: 0 }); // 0 for Sunday

export const initialShifts: Shift[] = [
  // Patient 123 - Has active and pending shifts
  { id: 'shift-001', patientId: 'patient-123', professionalId: 'prof-1', dayKey: format(startOfCurrentWeek, 'yyyy-MM-dd'), shiftType: 'diurno', status: 'in_progress', progress: 50, checkIn: '08:02', checkInStatus: 'OK' },
  { id: 'shift-002', patientId: 'patient-123', dayKey: format(startOfCurrentWeek, 'yyyy-MM-dd'), shiftType: 'noturno', status: 'published' },
  { id: 'shift-003', patientId: 'patient-123', professionalId: 'prof-3', dayKey: format(addDays(startOfCurrentWeek, 1), 'yyyy-MM-dd'), shiftType: 'diurno', status: 'assigned' },
  { id: 'shift-004', patientId: 'patient-123', professionalId: 'prof-5', dayKey: format(addDays(startOfCurrentWeek, 1), 'yyyy-MM-dd'), shiftType: 'noturno', status: 'assigned' },

  // Patient 456 - Has open, urgent, and completed shifts
  { id: 'shift-005', patientId: 'patient-456', dayKey: format(startOfCurrentWeek, 'yyyy-MM-dd'), shiftType: 'diurno', status: 'scheduled', isUrgent: true },
  { id: 'shift-006', patientId: 'patient-456', professionalId: 'prof-5', dayKey: format(startOfCurrentWeek, 'yyyy-MM-dd'), shiftType: 'noturno', status: 'cancelled', progress: 90, checkIn: '20:00', checkInStatus: 'OK', hasNotification: true },
  { id: 'shift-007', patientId: 'patient-456', professionalId: 'prof-6', dayKey: format(addDays(startOfCurrentWeek, -1), 'yyyy-MM-dd'), shiftType: 'diurno', status: 'completed', progress: 100, checkIn: '08:00', checkOut: '20:00', checkInStatus: 'OK', checkOutStatus: 'OK' },

  // Patient 789 - Mostly filled
  { id: 'shift-008', patientId: 'patient-789', professionalId: 'prof-2', dayKey: format(startOfCurrentWeek, 'yyyy-MM-dd'), shiftType: 'diurno', status: 'in_progress', progress: 30, checkIn: '07:55', checkInStatus: 'OK' },
  { id: 'shift-009', patientId: 'patient-789', professionalId: 'prof-7', dayKey: format(startOfCurrentWeek, 'yyyy-MM-dd'), shiftType: 'noturno', status: 'assigned' },
  { id: 'shift-010', patientId: 'patient-789', dayKey: format(addDays(startOfCurrentWeek, 2), 'yyyy-MM-dd'), shiftType: 'diurno', status: 'scheduled' },
];

export const mockShiftHistory: ShiftHistoryEvent[] = [
    { time: '08:02', event: 'Início do Plantão', details: 'Profissional iniciou o plantão via app.', icon: Clock, status: 'ok' },
    { time: '08:15', event: 'Check-in Realizado', details: 'Presença confirmada na residência.', icon: CircleCheck, status: 'ok' },
    { time: '09:00', event: 'Medicação Administrada', details: 'Administrado Losartana 50mg e Metformina 850mg.', icon: Pill, status: 'ok' },
    { time: '11:30', event: 'Consulta Médica', details: 'Reavaliação de rotina. PA estável. Solicitado novo exame de sangue.', icon: Stethoscope, status: 'pending' },
    { time: '14:00', event: 'Coleta para Exame', details: 'Coleta de sangue para hemograma completo e glicemia.', icon: TestTube, status: 'pending' },
    { time: '20:05', event: 'Check-out', details: 'Aguardando confirmação de saída.', icon: CircleX, status: 'late' },
    { time: '20:10', event: 'Fim do Plantão', details: 'Aguardando finalização do plantão.', icon: Clock, status: 'late' },
];

export const mockInventory: InventoryItem[] = [
  { id: 'item-001', patientId: 'patient-123', supplyId: 'supply-001', name: 'Gaze Estéril', description: 'Pacote com 10 unidades 10x10cm', stock: 45, lowStockThreshold: 20 },
  { id: 'item-002', patientId: 'patient-123', supplyId: 'supply-002', name: 'Pomada Antibiótica', description: 'Tubo de 30g', stock: 8, lowStockThreshold: 5 },
  { id: 'item-003', patientId: 'patient-123', supplyId: 'supply-003', name: 'Fita Micropore', description: 'Rolo de 2.5cm x 10m', stock: 12, lowStockThreshold: 10 },
  { id: 'item-004', patientId: 'patient-456', supplyId: 'supply-004', name: 'Luvas Descartáveis', description: 'Caixa com 100un, tamanho M', stock: 88, lowStockThreshold: 50 },
  { id: 'item-005', patientId: 'patient-456', supplyId: 'supply-005', name: 'Soro Fisiológico', description: 'Frasco de 500ml', stock: 3, lowStockThreshold: 4 },
  { id: 'item-006', patientId: 'patient-789', supplyId: 'supply-006', name: 'Seringas', description: '10ml, bico Luer Lock, caixa c/ 50', stock: 2, lowStockThreshold: 30 },
  { id: 'item-007', patientId: 'patient-789', supplyId: 'supply-007', name: 'Curativos Adesivos', description: 'Caixa com tamanhos variados', stock: 150, lowStockThreshold: 50 },
  { id: 'item-008', patientId: 'patient-789', supplyId: 'supply-008', name: 'Álcool 70%', description: 'Frasco de 1L', stock: 1, lowStockThreshold: 2 },
];

export const mockSupplyRequests: SupplyRequest[] = [
  {
    id: 'req-001',
    patientId: 'patient-123',
    supplyId: 'supply-001',
    quantityRequested: 30,
    requestDate: subDays(new Date(), 2).toISOString(),
    status: 'pending',
    notes: 'Repor estoque para curativos da semana.'
  },
  {
    id: 'req-002',
    patientId: 'patient-123',
    supplyId: 'supply-002',
    quantityRequested: 5,
    requestDate: subDays(new Date(), 5).toISOString(),
    status: 'approved',
    notes: 'Solicitado pela enfermeira Carla.'
  },
  {
    id: 'req-003',
    patientId: 'patient-456',
    supplyId: 'supply-005',
    quantityRequested: 10,
    requestDate: subDays(new Date(), 1).toISOString(),
    status: 'pending'
  },
];

export const mockShiftReports: ShiftReport[] = [
  {
    id: 'sr-001',
    patientId: 'patient-123',
    careTeamMemberName: 'Carla Nogueira',
    shift: 'diurno',
    reportDate: new Date(new Date().setDate(new Date().getDate() -1)).toISOString(),
    observations: 'Paciente passou o dia tranquilo, colaborativo e sem queixas de dor. Realizou fisioterapia pela manhã e aceitou bem a dieta.',
    vitalSigns: { bloodPressure: '122/78', heartRate: 75, oxygenSaturation: 98 }
  },
  {
    id: 'sr-002',
    patientId: 'patient-123',
    careTeamMemberName: 'Fábio Bastos',
    shift: 'noturno',
    reportDate: new Date(new Date().setDate(new Date().getDate() -2)).toISOString(),
    observations: 'Noite calma, sono tranquilo com alguns despertares. Sem intercorrências durante a madrugada. Sinais vitais estáveis.',
    vitalSigns: { bloodPressure: '118/75', heartRate: 70, oxygenSaturation: 97 }
  },
  {
    id: 'sr-003',
    patientId: 'patient-456',
    careTeamMemberName: 'Diogo Lima',
    shift: 'diurno',
    reportDate: new Date(new Date().setDate(new Date().getDate() -1)).toISOString(),
    observations: 'Paciente apresentou leve dor na articulação do joelho direito. Administrado analgésico conforme prescrição, com melhora do quadro.',
    vitalSigns: { bloodPressure: '130/85', heartRate: 80, oxygenSaturation: 99 }
  }
]

export const mockNotifications: Notification[] = [
  {
    id: 'notif-001',
    patientId: 'patient-123',
    type: 'supply',
    message: 'Solicitação de Soro Fisiológico (2 unidades) enviada para a família.',
    timestamp: new Date(new Date().setHours(new Date().getHours() - 2)).toISOString(),
    read: false,
  },
  {
    id: 'notif-002',
    patientId: 'patient-123',
    type: 'alert',
    message: 'Nível de estoque de Seringas está crítico (2 unidades).',
    timestamp: new Date(new Date().setHours(new Date().getHours() - 5)).toISOString(),
    read: false,
  },
    {
    id: 'notif-003',
    patientId: 'patient-456',
    type: 'info',
    message: 'Profissional Carla Nogueira confirmou o plantão de amanhã.',
    timestamp: new Date(new Date().setDate(new Date().getDate() -1)).toISOString(),
    read: true,
  },
  {
    id: 'notif-004',
    patientId: 'patient-123',
    type: 'info',
    message: 'Família confirmou a compra dos medicamentos solicitados.',
    timestamp: new Date(new Date().setHours(new Date().getHours() - 1)).toISOString(),
    read: false,
  }
];

export const mockTasks: Task[] = [
    { id: 'task-1', title: 'Revisar prontuário do novo paciente Sr. Jorge', description: 'Verificar todo o histórico médico, alergias e medicamentos em uso do paciente Jorge Mendes para garantir que a transição para o home care seja segura.', assignee: 'Admin', priority: 'Alta', status: 'todo', patientId: 'patient-789' },
    { id: 'task-2', title: 'Aprovar candidaturas para o plantão de sexta-feira', description: 'Analisar o perfil dos candidatos e selecionar o profissional mais adequado para o plantão do paciente João da Silva.', assignee: 'Admin', priority: 'Urgente', status: 'inprogress' },
    { id: 'task-3', title: 'Ligar para a família da Sra. Maria Lopes sobre o novo medicamento', description: 'Entrar em contato com o Sr. Carlos Lopes para explicar a nova prescrição de Metotrexato e orientar sobre a administração semanal.', assignee: 'Enf. Chefe', priority: 'Alta', status: 'todo', patientId: 'patient-456' },
    { id: 'task-4', title: 'Organizar a escala da próxima semana', description: 'Montar a grade de horários de todos os pacientes, garantindo a cobertura de todos os plantões, diurnos e noturnos.', assignee: 'Admin', priority: 'Média', status: 'done', dueDate: new Date(new Date().setDate(new Date().getDate() - 3)).toISOString() },
    { id: 'task-5', title: 'Verificar estoque de gaze para o Sr. João', description: 'Contar a quantidade de pacotes de gaze estéril no inventário do paciente João da Silva e solicitar reposição se necessário.', assignee: 'Enf. Chefe', priority: 'Média', status: 'todo', patientId: 'patient-123', dueDate: new Date().toISOString() }
];

export const mockTransactions: Transaction[] = [
  {
    id: 'tx-001',
    patientId: 'patient-123',
    provider: 'Cora',
    providerTxId: 'cora-8811',
    amount: 8500,
    currency: 'BRL',
    status: 'paid',
    method: 'pix',
    dueDate: format(subMonths(today, 0), 'yyyy-MM-05'),
    paidAt: format(subDays(today, 2), "yyyy-MM-dd'T'HH:mm:ssxxx"),
    createdAt: format(subMonths(today, 0), "yyyy-MM-dd'T'HH:mm:ssxxx"),
    metadata: { description: 'Fatura ref. Julho' },
  },
  {
    id: 'tx-002',
    patientId: 'patient-456',
    provider: 'Stripe',
    providerTxId: 'stripe-2244',
    amount: 4200,
    currency: 'BRL',
    status: 'pending',
    method: 'card',
    dueDate: format(addDays(today, 3), 'yyyy-MM-dd'),
    createdAt: format(subDays(today, 1), "yyyy-MM-dd'T'HH:mm:ssxxx"),
    metadata: { description: 'Fatura aguardando confirmação' },
  },
  {
    id: 'tx-003',
    patientId: 'patient-789',
    provider: 'Asaas',
    providerTxId: 'asaas-9933',
    amount: 12900,
    currency: 'BRL',
    status: 'overdue',
    method: 'boleto',
    dueDate: format(subDays(today, 5), 'yyyy-MM-dd'),
    createdAt: format(subDays(today, 12), "yyyy-MM-dd'T'HH:mm:ssxxx"),
    metadata: { description: 'Plano premium - Junho' },
  },
  {
    id: 'tx-004',
    patientId: 'patient-123',
    provider: 'PicPay',
    providerTxId: 'picpay-777',
    amount: 2100,
    currency: 'BRL',
    status: 'cancelled',
    method: 'pix',
    dueDate: format(subMonths(today, 1), 'yyyy-MM-28'),
    createdAt: format(subMonths(today, 1), "yyyy-MM-dd'T'HH:mm:ssxxx"),
    metadata: { description: 'Cancelada pelo cliente' },
  },
].sort((a, b) => new Date(b.createdAt ?? 0).getTime() - new Date(a.createdAt ?? 0).getTime());

export const mockMonthlyRevenue = [
  { month: format(subMonths(today, 5), 'MMM', { locale: ptBR }), revenue: 15200 },
  { month: format(subMonths(today, 4), 'MMM', { locale: ptBR }), revenue: 17800 },
  { month: format(subMonths(today, 3), 'MMM', { locale: ptBR }), revenue: 16500 },
  { month: format(subMonths(today, 2), 'MMM', { locale: ptBR }), revenue: 19800 },
  { month: format(subMonths(today, 1), 'MMM', { locale: ptBR }), revenue: 21500 },
  { month: format(today, 'MMM', { locale: ptBR }), revenue: 10650 },
];



