/**
 * =================================================================================================
 *
 * 🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑
 *
 * THIS FILE IS THE SINGLE SOURCE OF TRUTH FOR ALL DATA STRUCTURES.
 *
 * 🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑
 *
 * It is autogenerated from the database schema.
 *
 * ANY MANUAL CHANGES WILL BE OVERWRITTEN.
 *
 * =================================================================================================
 */

// -----------------------------------------------------------------------------------------------
// #region ENUMS & LITERALS
// -----------------------------------------------------------------------------------------------

export type UserRole = 'admin' | 'coordinator' | 'professional' | 'viewer';
export type ShiftStatus = 'scheduled' | 'published' | 'assigned' | 'in_progress' | 'completed' | 'cancelled';
export type PresenceState = 'offline' | 'online' | 'on_break' | 'unresponsive';
export type PatientRecordStatus = 'active' | 'inactive' | 'discharged' | 'deceased';
export type SupplyRequestStatus = 'pending' | 'approved' | 'denied' | 'fulfilled' | 'cancelled';

export type PatientDocumentType = 'RG' | 'CPF' | 'CNH' | 'ComprovanteResidencia' | 'CarteirinhaPlano' | 'ContratoPrestacaoServicos' | 'AditivoContrato' | 'LaudoMedico' | 'RelatorioTecnico' | 'ReceitaMedica' | 'TermoConsentimento' | 'TermoResponsabilidade' | 'POA' | 'Outro';
export type PatientDocumentCategory = 'Identificacao' | 'Financeiro' | 'Clinico' | 'Juridico' | 'Consentimento' | 'Outros';
export type PatientDocumentSource = 'upload' | 'integracao' | 'assinaturaDigital' | 'importacao';

export type PatientConsentType = 'TratamentoDadosLGPD' | 'CompartilhamentoComOperadora' | 'CompartilhamentoComFamiliares' | 'EnvioComunicacoesWhatsApp' | 'AutorizacaoProcedimentoInvasivo' | 'AutorizacaoPublicacaoImagem' | 'Outro';
export type PatientConsentScope = 'DadosClinicos' | 'DadosFinanceiros' | 'DadosAdministrativos' | 'EnvioComunicacoes' | 'CompartilhamentoComTerceiros' | 'Imagem' | 'Outros';
export type PatientConsentStatus = 'Ativo' | 'Revogado' | 'Expirado';
export type PatientConsentChannel = 'AssinaturaDigital' | 'Upload' | 'Aplicativo' | 'Manual';
export type PatientConsentGrantedBy = 'Paciente' | 'ResponsavelLegal' | 'Tutor' | 'Outro';
export type PaymentTransactionStatus = 'pending' | 'paid' | 'failed' | 'cancelled' | 'overdue' | string;

export type PatientAuditEventType = 'view' | 'edit' | 'export' | 'download' | 'login_as_family' | 'status_change';
export type PatientAuditOrigin = 'web' | 'mobile' | 'api' | 'integration';

// #endregion

// -----------------------------------------------------------------------------------------------
// #region CORE TABLES
// -----------------------------------------------------------------------------------------------

export type Tenant = {
  id: string; // uuid
  name: string;
  createdAt: string; // timestamptz
};

export type UserProfile = {
  id: string; // uuid
  authUserId: string; // uuid
  email?: string | null;
  name?: string | null;
  phone?: string | null;
  role?: string | null;
  tenantId?: string | null; // uuid
  createdAt: string; // timestamptz
};

export type Patient = {
  id: string; // uuid
  tenantId: string; // uuid
  fullName: string;
  dateOfBirth?: string | null; // date
  cns?: string | null;
  cpf?: string | null;
  cpfStatus?: 'valid' | 'invalid' | 'unknown';
  rg?: string | null;
  rgIssuer?: string | null;
  rgDigitalUrl?: string | null;
  nationalId?: string | null;
  sexAtBirth?: 'M' | 'F' | 'Other' | 'Unknown';
  genderIdentity?: string | null;
  civilStatus?: string | null;
  nationality?: string | null;
  placeOfBirth?: string | null;
  pronouns?: string | null;
  photoUrl?: string | null;
  displayName?: string | null;
  name?: string | null;
  initials?: string | null;
  preferredLanguage?: string | null;
  preferredContactMethod?: string | null;
  recordStatus: 'active' | 'inactive' | 'deceased';
  riskFlags?: string[] | null;
  duplicateCandidates?: string[] | null;
  lastViewedAt?: string | null; // timestamptz
  createdAt: string; // timestamptz
  updatedAt?: string | null; // timestamptz
  createdBy?: string | null; // uuid
  updatedBy?: string | null; // uuid

  // JSONB fields
  phones?: { type: string; number: string; preferred: boolean; verified: boolean }[] | null;
  emails?: { email: string; preferred: boolean; verified: boolean }[] | null;
  externalIds?: Record<string, any> | null;
  identityVerification?: Record<string, any> | null;
  documentValidation?: Record<string, any> | null;
  sensitiveDataConsent?: Record<string, any> | null;
  photoConsent?: Record<string, any> | null;
  communicationOptOut?: Record<string, any> | null;
  accessLogSummary?: Record<string, any> | null;
  emergencyContacts?: Record<string, any>[] | null;
  legalGuardian?: Record<string, any> | null;
  // UI-composite fields (from related tables) kept optional for backward compatibility
  address?: PatientAddress | Record<string, any> | null;
  domicile?: Record<string, any> | null;
  adminData?: Record<string, any> | null;
  financial?: Record<string, any> | null;
  clinicalSummary?: Record<string, any> | null;
  clinicalSummaryMeta?: Record<string, any> | null;
  documentsCollection?: PatientDocument[];
  changeLog?: PatientAuditLog[];
  accessLog?: PatientAuditLog[];
  smartFields?: Record<string, any> | null;
  pending_documents?: number;
  consent_status?: 'ok' | 'pending';
  last_visit_date?: string | null;
  next_visit_date?: string | null;
};

export type Professional = {
  id: string; // uuid
  tenantId: string; // uuid
  fullName: string;
  registryCode?: string | null;
  specialties: string[];
  phone?: string | null;
  email?: string | null;
  avatarUrl?: string | null;
  notes?: string | null;
  employmentType?: string | null;
  createdAt: string; // timestamptz
  updatedAt: string; // timestamptz
};

export type Shift = {
  id: string; // uuid
  tenantId?: string | null; // uuid
  ownerId?: string | null; // uuid
  title?: string;
  description?: string | null;
  startAt?: string | null; // timestamptz
  endAt?: string | null; // timestamptz
  status: ShiftStatus;
  createdAt?: string | null; // timestamptz
  updatedAt?: string | null; // timestamptz
  // UI/legacy fields still in use on the client side
  patientId?: string;
  professionalId?: string;
  dayKey?: string;
  shiftType?: 'diurno' | 'noturno';
  isUrgent?: boolean;
  progress?: number;
  checkIn?: string | null;
  checkOut?: string | null;
  checkInStatus?: 'OK' | 'Pendente' | 'Falha';
  checkOutStatus?: 'OK' | 'Pendente' | 'Falha';
  hasNotification?: boolean;
};

export type Post = {
  id: string; // uuid
  tenantId?: string | null; // uuid
  authorId?: string | null; // uuid
  shiftId?: string | null; // uuid
  content?: string | null;
  pinned: boolean;
  createdAt: string; // timestamptz
};

export type Presence = {
  id: string; // uuid
  tenantId?: string | null; // uuid
  userId?: string | null; // uuid
  shiftId?: string | null; // uuid
  state: PresenceState;
  lastSeen: string; // timestamptz
};

export type InventoryItem = {
  id: string; // uuid
  tenantId?: string | null; // uuid
  name: string;
  unit?: string | null;
  minStock?: number | null;
  createdAt: string; // timestamptz
};

export type SupplyRequest = {
  id: string; // uuid
  tenantId?: string | null; // uuid
  requesterId?: string | null; // uuid
  itemId?: string | null; // uuid
  shiftId?: string | null; // uuid
  status: SupplyRequestStatus;
  qty: number;
  createdAt: string; // timestamptz
};

export type AuditLog = {
  id: number; // bigserial
  tenantId?: string | null; // uuid
  entity?: string | null;
  entityId?: string | null; // uuid
  action?: string | null;
  actorId?: string | null; // uuid
  payload?: Record<string, any> | null;
  createdAt: string; // timestamptz
};

// #endregion

// -----------------------------------------------------------------------------------------------
// #region PATIENT-RELATED TABLES
// -----------------------------------------------------------------------------------------------

export type PatientAddress = {
  id: string; // uuid
  tenantId: string; // uuid
  patientId: string; // uuid
  cep?: string | null;
  addressLine?: string | null;
  number?: string | null;
  complement?: string | null;
  neighborhood?: string | null;
  city?: string | null;
  state?: string | null;
  referencePoint?: string | null;
  geoLat?: number | null;
  geoLng?: number | null;
  zoneType?: string | null;
  gatehouseName?: string | null;
  facadePhotoUrl?: string | null;
  residenceType?: string | null;
  floor?: number | null;
  internalAccess?: string | null;
  stayLocation?: string | null;
  electricInfra?: string | null;
  waterSource?: string | null;
  hasWifi?: boolean | null;
  backupPower?: string | null;
  adaptedBathroom?: boolean | null;
  ambulanceAccess?: string | null;
  parking?: string | null;
  entryProcedure?: string | null;
  avgEtaMin?: number | null;
  worksOrObstacles?: string | null;
  nightAccessRisk?: string | null;
  ventilation?: string | null;
  noiseLevel?: string | null;
  hasSmokers?: boolean | null;
  hygieneRating?: string | null;
  notes?: string | null;
  createdAt: string; // timestamptz
  updatedAt?: string | null; // timestamptz

  // JSONB fields
  visitHours?: Record<string, any> | null;
  localSecurity?: string[] | null;
  accessibility?: Record<string, any> | null;
  pets?: Record<string, any> | null;
  residents?: Record<string, any> | null;
  caregivers?: Record<string, any> | null;
  environmentalRisk?: string[] | null;
};

export type PatientAdminInfo = {
  patientId: string; // uuid
  tenantId: string; // uuid
  status?: string | null;
  admissionType?: string | null;
  complexity?: string | null;
  servicePackage?: string | null;
  startDate?: string | null; // date
  endDate?: string | null; // date
  supervisorId?: string | null; // uuid
  escalistaId?: string | null; // uuid
  nurseResponsibleId?: string | null; // uuid
  frequency?: string | null;
  operationArea?: string | null;
  admissionSource?: string | null;
  contractId?: string | null;
  lastAuditDate?: string | null; // date
  lastAuditBy?: string | null; // uuid
  notesInternal?: string | null;
  createdAt: string; // timestamptz
  updatedAt?: string | null; // timestamptz
  lastUpdateBy?: string | null;
  meta?: Record<string, any> | null;
};

export type PatientClinicalSummary = {
  patientId: string; // uuid
  tenantId: string; // uuid
  summary: Record<string, any>;
  meta?: Record<string, any> | null;
  updatedAt: string; // timestamptz
};

export type PatientFinancialInfo = {
  id: string; // uuid
  patientId: string; // uuid
  tenantId: string; // uuid
  bondType?: string | null;
  insurer?: string | null;
  planName?: string | null;
  cardNumber?: string | null;
  validity?: string | null; // date
  monthlyFee?: number | null;
  dueDay?: number | null;
  paymentMethod?: string | null;
  billingStatus?: string | null;
  lastPaymentDate?: string | null; // date
  lastPaymentAmount?: number | null;
  financialContact?: string | null;
  observations?: string | null;
  invoiceHistory?: Record<string, any>[] | null;
  createdAt: string; // timestamptz
  updatedAt: string; // timestamptz
  meta?: Record<string, any> | null;
};

export type PatientSupportNetwork = {
  id: string; // uuid
  patientId: string; // uuid
  tenantId: string; // uuid
  notesSupport?: string | null;
  createdAt: string; // timestamptz
  updatedAt: string; // timestamptz

  // JSONB fields
  responsibleLegal?: Record<string, any> | null;
  network?: Record<string, any>[] | null;
  emergencyContact?: Record<string, any> | null;
};

export type PatientDocument = {
  id: string; // uuid
  patientId: string; // uuid
  type: PatientDocumentType;
  category: PatientDocumentCategory;
  title: string;
  description?: string | null;
  fileUrl: string;
  fileName?: string | null;
  mimeType?: string | null;
  fileHash?: string | null;
  uploadedBy?: string | null; // uuid
  uploadedAt: string; // timestamptz
  expiresAt?: string | null; // date
  source: PatientDocumentSource;
  verified: boolean;
  verifiedBy?: string | null; // uuid
  verifiedAt?: string | null; // timestamptz
  tags?: string[] | null;
  metadata?: Record<string, any> | null;
  createdAt: string; // timestamptz
};

export type PatientConsent = {
  id: string; // uuid
  patientId: string; // uuid
  type: PatientConsentType;
  status: PatientConsentStatus;
  scope: PatientConsentScope[];
  channel: PatientConsentChannel;
  grantedAt: string; // timestamptz
  revokedAt?: string | null; // timestamptz
  documentId?: string | null; // uuid
  grantedBy: PatientConsentGrantedBy;
  grantedByName: string;
  grantedByDocument?: string | null;
  relatedLegalResponsibleId?: string | null; // uuid
  notes?: string | null;
  metadata?: Record<string, any> | null;
};

export type PatientAuditLog = {
  id: string; // uuid
  patientId: string; // uuid
  type: PatientAuditEventType;
  action: string;
  userId?: string | null; // uuid
  userRole?: string | null;
  eventTime: string; // timestamptz
  origin: PatientAuditOrigin;
  ip?: any | null; // inet
  changedFields?: string[] | null;
  oldValue?: Record<string, any> | null;
  newValue?: Record<string, any> | null;
  meta?: Record<string, any> | null;
};

export type PatientIntelligence = {
  patientId: string; // uuid
  readmissionRiskScore?: number | null;
  readmissionRiskLabel?: string | null;
  readmissionRiskSource?: string | null;
  readmissionRiskUpdatedAt?: string | null; // timestamptz
  careAdherenceScore?: number | null;
  careAdherenceLabel?: string | null;
  careAdherenceUpdatedAt?: string | null; // timestamptz
  familySatisfactionScore?: number | null;
  familySatisfactionLabel?: string | null;
  familySatisfactionSource?: string | null;
  familySatisfactionUpdatedAt?: string | null; // timestamptz
  incidentsLast30Days?: number | null;
  lastIncidentAt?: string | null; // date
  extraInsights?: Record<string, any> | null;
  createdAt: string; // timestamptz
  updatedAt: string; // timestamptz
};

export type PatientOperationalLinks = {
  patientId: string; // uuid
  contractId?: string | null; // uuid
  rosterId?: string | null; // uuid
  inventoryProfileId?: string | null; // uuid
  publicProtocolUrl?: string | null;
  publicProtocolToken?: string | null;
  publicProtocolCreatedAt?: string | null; // timestamptz
  externalCrmId?: string | null;
  externalEmrId?: string | null;
  accessLogRef?: string | null;
  extraLinks?: Record<string, any> | null;
  createdAt: string; // timestamptz
  updatedAt: string; // timestamptz
};

// #endregion

// -----------------------------------------------------------------------------------------------
// #region SECURITY & MEMBERSHIP TABLES
// -----------------------------------------------------------------------------------------------

export type Role = {
  id: string; // uuid
  key: string;
  name: string;
  description?: string | null;
  createdAt: string; // timestamptz
};

export type UserRoleLink = {
  userId: string; // uuid
  roleId: string; // uuid
  grantedAt: string; // timestamptz
  grantedBy?: string | null; // uuid
  scope: string;
  metadata?: Record<string, any> | null;
};

export type PatientMembership = {
  id: string; // uuid
  patientId: string; // uuid
  userId: string; // uuid
  relationship?: string | null;
  permissions: Record<string, any>;
  invitedBy?: string | null; // uuid
  createdAt: string; // timestamptz
  updatedAt: string; // timestamptz
  active: boolean;
};

export type DataExportRequest = {
  id: string; // uuid
  patientId: string; // uuid
  requestedByUser: string; // uuid
  requestType: string;
  status: string;
  createdAt: string; // timestamptz
  processedAt?: string | null; // timestamptz
  resultLocation?: string | null;
  reasonRejected?: string | null;
  metadata?: Record<string, any> | null;
};

// #endregion

// -----------------------------------------------------------------------------------------------
// #region INTEGRATION & LOGGING TABLES
// -----------------------------------------------------------------------------------------------

export type AppEvent = {
  id: string; // uuid
  occurredAt: string; // timestamptz
  eventName: string;
  userId?: string | null; // uuid
  patientId?: string | null; // uuid
  source?: string | null;
  userRole?: string | null;
  context?: Record<string, any> | null;
  metadata?: Record<string, any> | null;
};

export type IntegrationConfig = {
  id: string; // uuid
  type: string;
  provider: string;
  config: Record<string, any>;
  active: boolean;
  createdAt: string; // timestamptz
  updatedAt: string; // timestamptz
};

export type WhatsappMessageLog = {
  id: string; // uuid
  patientId?: string | null; // uuid
  toPhone: string;
  templateName?: string | null;
  direction: string;
  messageType: string;
  bodyPreview?: string | null;
  status: string;
  providerMsgId?: string | null;
  errorCode?: string | null;
  errorMessage?: string | null;
  metadata?: Record<string, any> | null;
  createdAt: string; // timestamptz
};

export type SignatureRequest = {
  id: string; // uuid
  patientId?: string | null; // uuid
  documentId?: string | null; // uuid
  provider: string;
  providerRequestId?: string | null;
  status: string;
  signers: Record<string, any>;
  callbackPayload?: Record<string, any> | null;
  createdAt: string; // timestamptz
  updatedAt: string; // timestamptz
};

export type RoutingLog = {
  id: string; // uuid
  patientId?: string | null; // uuid
  fromLocation: Record<string, any>;
  toLocation: Record<string, any>;
  provider: string;
  distanceKm?: number | null;
  etaMinutes?: number | null;
  mode?: string | null;
  createdAt: string; // timestamptz
};

export type PaymentTransaction = {
  id: string; // uuid
  patientId?: string | null; // uuid
  provider: string;
  providerTxId?: string | null;
  amount: number;
  currency?: string | null;
  status: PaymentTransactionStatus;
  method?: string | null;
  dueDate?: string | null; // date
  paidAt?: string | null; // timestamptz
  metadata?: Record<string, any> | null;
  createdAt: string; // timestamptz
};

export type Transaction = PaymentTransaction;

export type OcrJob = {
  id: string; // uuid
  documentId: string; // uuid
  provider: string;
  status: string;
  extractedData?: Record<string, any> | null;
  errorMessage?: string | null;
  createdAt: string; // timestamptz
  updatedAt: string; // timestamptz
};

export type FrontendErrorLog = {
  id: string; // uuid
  userId?: string | null; // uuid
  context?: Record<string, any> | null;
  message?: string | null;
  stack?: string | null;
  severity?: string | null;
  createdAt: string; // timestamptz
};

// #endregion

// -----------------------------------------------------------------------------------------------
// #region COMPOSITE & UI-SPECIFIC TYPES
// -----------------------------------------------------------------------------------------------

/**
 * @deprecated This type is a Frankenstein's monster of old and new schemas.
 * It will be removed. Use the new specific types instead.
 * For UI, create a composite type that combines the new types as needed.
 */
export type LegacyPatient = any; // The old Patient type is now 'any' to force migration.

/**
 * A composite type for displaying a comprehensive patient view in the UI.
 * This combines the core patient data with related information.
 */
export type PatientProfile = Patient & {
  address?: PatientAddress;
  adminInfo?: PatientAdminInfo;
  clinicalSummary?: PatientClinicalSummary;
  financialInfo?: PatientFinancialInfo;
  supportNetwork?: PatientSupportNetwork;
  intelligence?: PatientIntelligence;
  operationalLinks?: PatientOperationalLinks;
  documents?: PatientDocument[];
  consents?: PatientConsent[];
  auditLogs?: PatientAuditLog[];
};

// Other UI-specific types can be defined below as needed.
// Example:
export type ShiftWithProfessional = Shift & {
  professional?: Professional;
};
